### ISSUE TITLE
[BUG] Html Editor Not working on Android

### ISSUE THREAD

**Issue by AxitGondaliya** [tneotia/html-editor-enhanced#537]
Not able to type anything when click on editor and when I am applying any style on getting initialize issue, please provide solution

![Uploading image.png…]()

**Comment by ygoncharenkofwd** [comment]
For me it helped to use these dependency overrides:
```
dependency_overrides:
  flutter_inappwebview_android:
    git:
      url: https://github.com/holzgeist/flutter_inappwebview
      path: flutter_inappwebview_android
      ref: d89b1d32638b49dfc58c4b7c84153be0c269d057
  flutter_inappwebview_ios:
    git:
      url: https://github.com/andychucs/flutter_inappwebview
      path: flutter_inappwebview_ios
      ref: master
  webview_flutter_android: 3.16.1
```

The iOS one is to make it build with XCode 16, the other 2 are to fix Android build
